### ISSUE TITLE
Generate list of block numbers

### ISSUE THREAD

**Issue by StayFoolisj** [monosux/ethereum-block-by-date#11]
Interesting library! How do I generate a list of block numbers for every single date for the past 3 years? 

![Screenshot 2021-05-14 at 13 12 47](https://user-images.githubusercontent.com/42708283/118224941-afb73880-b4b6-11eb-869e-27484f3da14d.png)

**Comment by monosux** [comment]
Hi,

what do you mean? Like first blocks of every day during 3 years? If so, try something like this:

```javascript
    let blocks = await dater.getEvery(
        'days',
        '2019-09-01T12:00:00Z', // put start date here,
        '2019-09-30T12:00:00Z' // put end date here
    );
```

**Comment by monosux** [comment]
It will return you something like this:

```javascript

[
  {
    date: '2019-09-01T12:00:00Z', // searched date
    block: 8464234, // found block number
    timestamp: 1567339207 // found block timestamp
  },
  {
    date: '2019-09-02T12:00:00Z',
    block: 8470641,
    timestamp: 1567425601
  },
  {
    date: '2019-09-03T12:00:00Z',
    block: 8477057,
    timestamp: 1567512020
  },
  ...
]

```

**Comment by monosux** [comment]
Hi, @StayFoolisj I am closing the issue, feel free to contact me if you have more questions.
