### ISSUE TITLE
Getting Date by Block

### ISSUE THREAD

**Issue by rvmelkonian** [monosux/ethereum-block-by-date#14]
Thanks for this great package. I've got a bunch of blocks and wondering if there is a method to get the date by block, rather than block by date?

**Comment by monosux** [comment]
Hi @rvmelkonian,

that is easy, web3 has the 'getBlock()' function, it returns information about the needed block, including blocks timestamp. Take a look: https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#getblock

```javascript

web3.eth.getBlock(3150)
.then(console.log);

// will return:

{
   ...
    "timestamp": 1429287689,
   ...
}

```
