### ISSUE TITLE
How to get list of all the blocks for given time span ?

### ISSUE THREAD

**Issue by saanvijay** [monosux/ethereum-block-by-date#21]
How to get list of all unique blocks for the given time span for a particular wallet? for example I want to get list of all unique blocks in the last 1 hour or list of all blocks between 11am - 12am today for wallet 0x123456789?

**Comment by monosux** [comment]
Hi @saanvijay,

My package can find a block for a given date, but not transactions for a given address.

>  all blocks between 11am - 12am today for wallet 0x123456789

Using my package you can find all blocks between 11am - 12am today, but not blocks containing transactions associated with wallet 0x123456789

For finding transactions associated with a wallet you need to find/create another solution. Something like this: https://gist.github.com/ross-p/bd5d4258ac23319f363dc75c2b722dd9
