### ISSUE TITLE
Feature Request: Viem compatibility

### ISSUE THREAD

**Issue by jd1900** [monosux/ethereum-block-by-date#50]
Viem is getting more and more attraction.

Could you add Viem compatibility?

**Comment by plandino** [comment]
Added support for Viem in this PR: https://github.com/monosux/ethereum-block-by-date/pull/54

**Comment by monosux** [comment]
Hi,

@jd1900 I just published version 1.5.0 with viem support. Please update.

@plandino Thank you for the temporary solution!
