### ISSUE TITLE
TypeError: Cannot read property 'getBlockNumber' of undefined

### ISSUE THREAD

**Issue by jsmellz** [monosux/ethereum-block-by-date#8]
Hi I'm running into this error. Thanks in advance! Code snippet below.

```
const dater = new EthDater(getNetworkLibrary())

  const [value, onChange] = useState(new Date())

  const getBlock = async () => {
    // Getting block by date:
    if (!dater) return;
    let block = await dater.getDate(
      value, // Date, required. Any valid moment.js value: string, milliseconds, Date() object, moment() object.
      true, // Block after, optional. Search for the nearest block before or after the given date. By default true.
    )

    console.log('BLOCK NUMBER', block, value)
  }
```

ERROR Pointing here
```
  29 | 
  30 |     if (!dater) return;
> 31 |     let block = await dater.getDate(
     |                           ^
  32 |         '2016-07-20T13:20:40Z', // Date, required. Any valid moment.js value: string, milliseconds, Date() object, moment() object.
  33 |         true // Block after, optional. Search for the nearest block before or after the given date. By default true.
  34 |     );
```

**Comment by monosux** [comment]
Hi,

looks like the 'getNetworkLibrary()' function you use returns not a valid web3 object. 

What is getNetworkLibrary() and what it returns?

**Comment by monosux** [comment]
Hi,

Looks like the problem doesn't connect with the package but with the 'getNetworkLibrary()' function. 

I am closing the issue for now. If you have any updates please feel free to add them.

**Comment by jsmellz** [comment]
Hi! The getNetworkLibrary() returns a web 3 provider. Is that not what should be passed in?

**Comment by monosux** [comment]
> Hi! The getNetworkLibrary() returns a web 3 provider. Is that not what should be passed in?

No, you need to pass a web3 object. What lib do you use? web3.js or ethers.js or something else?

**Comment by jsmellz** [comment]
I'm using ethers.JS.

**Comment by jsmellz** [comment]
I'd be very glad if you could share an example usage of ethers.JS. 😊

**Comment by monosux** [comment]
Sure,

This code is working with ethers.js:

```
const { ethers } = require("ethers");
const ethDater = require("ethereum-block-by-date");

const ethers_provider = new ethers.providers.CloudflareProvider();

const dater = new ethDater({
    eth: ethers_provider
});
```

So with your code it should be:

```

const dater = new ethDater({
    eth: getNetworkLibrary()
});

```

Let me know if it works.

**Comment by monosux** [comment]
@jsmellz Any luck?
